apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.name}}
  labels:
    app: {{.Values.app.name}}
spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: {{.Values.app.name}}
  template:
    metadata:
      name: {{.Values.app.name}}
      labels:
        app: {{.Values.app.name}}
    spec:
      imagePullSecrets:
        - name: {{.Values.secrets.default}}
      containers:
        - name: {{.Values.app.name}}
          image: {{.Values.docker.img.repo}}:{{.Values.docker.img.name}}-{{.Values.docker.img.tag}}
          imagePullPolicy: Always
          ports:
            - containerPort: {{.Values.docker.img.port}}