apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - {{.Values.ingress.host}}
      secretName: {{.Values.ingress.secret}}
  rules:
    - host: {{.Values.ingress.host}}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{.Values.service.name}}
              servicePort: {{.Values.service.port}}